name: gaza_flutter_cleaner
description: Clean all your Flutter build folders with one command and save your disk space
version: 1.1.0
repository: https://github.com/EmadBeltaje/gaza_flutter_cleaner
homepage: https://github.com/EmadBeltaje/gaza_flutter_cleaner
documentation: https://github.com/EmadBeltaje/gaza_flutter_cleaner#readme
issue_tracker: https://github.com/EmadBeltaje/gaza_flutter_cleaner/issues
topics: [flutter, dart, cli, clean, clear]

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  path: ^1.8.0
  args: ^2.4.1
  mason_logger: ^0.2.1

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
  mockito: ^5.2.0

executables:
  gaza_flutter_cleaner: gaza_flutter_cleaner